app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(80))
    posts = db.relationship('Post', backref='author', lazy='dynamic')


class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256))
    subtitle = db.Column(db.String(256))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    date_posted = db.Column(db.DateTime)
    content = db.Column(db.Text)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SubmitField
from wtforms.validators import InputRequired, Email, Length

'''
Define form elements
'''


class LoginForm(FlaskForm):
    username = StringField("username", validators=[InputRequired(), Length(min=4, max=50)])
    password = PasswordField("password", validators=[InputRequired(), Length(min=9, max=80)])
    # remember = BooleanField("remember")
    submit = SubmitField("Sign in")


class SignupForm(FlaskForm):
    username = StringField("username", validators=[InputRequired(), Length(min=4, max=50)])
    email = StringField("email", validators=[InputRequired(),
                                             Email(message="Invalid email"),
                                             Length(max=80)])
    password = PasswordField("password", validators=[InputRequired(), Length(min=9, max=80)])
    submit = SubmitField("Create account")


class NewPostForm(FlaskForm):
    title = StringField("title", validators=[InputRequired(), Length(min=1, max=256)])
    subtitle = StringField("subtitle", validators=[InputRequired(), Length(min=1, max=256)])
    content = TextAreaField("subtitle", validators=[InputRequired()])
    submit = SubmitField("Publish")

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from config import config

login_manager = LoginManager()
migrate = Migrate()


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config[config_name])

    # configure appropriate environment
    config[config_name].init_app(app)

    # initialize database
    from app.models import db
    db.init_app(app)

    login_manager.init_app(app)
    login_manager.login_view = "app.login"

    from app.views import mod
    app.register_blueprint(mod)

    return app

app/views.py
from flask import Blueprint
from flask import render_template, redirect, flash, request, url_for, abort
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from app import login_manager
from app.models import db, User, Post
from app.forms import LoginForm, SignupForm, NewPostForm
from urllib.parse import urlparse, urljoin
from datetime import datetime

mod = Blueprint("app", __name__, template_folder="templates", static_folder="static")


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@mod.route("/")
def index():
    posts = Post.query.order_by(Post.date_posted.desc()).all()

    return render_template("index.html", posts=posts)


@mod.route("/about")
def about():
    return render_template("about.html")


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc


@mod.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                flash("Logged in successfully")

                # TODO: Fix 'next'
                """" 
                dest = request.args.get('next')
                # is_safe_url should check if the url is safe for redirects.
                # See http://flask.pocoo.org/snippets/62/ for an example.
                if not is_safe_url(dest):
                    return abort(400)
                """

                return redirect(url_for('app.index'))

    return render_template("login.html", form=form)


@mod.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method="sha256")
        new_user = User(username=form.username.data,
                        email=form.email.data,
                        password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('app.index'))

    return render_template("signup.html", form=form)


@mod.route("/post/<int:post_id>")
def post(post_id):
    blogpost = Post.query.filter_by(id=post_id).one()

    date = blogpost.date_posted.strftime('%B %d, %Y')

    return render_template("post.html", post=blogpost, date_posted=date)


@mod.route("/newpost", methods=["GET", "POST"])
@login_required
def new_post():
    form = NewPostForm()
    if form.validate_on_submit():
        blogpost = Post(title=form.title.data,
                        subtitle=form.subtitle.data,
                        author_id=current_user.id,
                        content=form.content.data,
                        date_posted=datetime.now())
        db.session.add(blogpost)
        db.session.commit()
        return redirect(url_for('app.index'))

    return render_template("newpost.html", form=form)


@mod.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have been logged out")
    return redirect(url_for('app.index'))

app/templates/about.html
{% extends "layouts/base.html" %}
{% block title %}
  About Me | The Pythonomicon
{% endblock %}

{% block content %}
<!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
        </div>
      </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "layouts/base.html" %}
{% block title %}
  Pythonomicon - By SmyhkTech
{% endblock %}

{% block content %}
<!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {% for post in posts %}
            <div class="post-preview">
              <a href="{{ url_for('app.post', post_id=post.id) }}">
                <h2 class="post-title">
                  {{ post.title }}
                </h2>
                <h3 class="post-subtitle">
                  {{ post.subtitle }}
                </h3>
              </a>
              <p class="post-meta">Posted by
                <a href="#">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
            </div>
          {% endfor %}
          <hr>

          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>
{% endblock %}

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" type="image/x-icon" href="{{ url_for('app.static', filename='img/favicon.ico') }}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='css/font-awesome.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/clean-blog.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('app.index') }}">Pythonomicon</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('app.index') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('app.about') }}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('app.new_post') }}">New Post</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/home-bg.jpg') }}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Pythonomicon</h1>
              <h3><em>noun</em> | pytho·nomi·con \'pithō, nämi, kän\</h3>
              <span class="subheading">A developer's journal documenting my experiences with Python.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; SmyhkTech 2017</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('static', filename='js/clean-blog.js') }}"></script>

  </body>

</html>

app/templates/login.html
{% extends "layouts/base.html" %}
{% block title %}
  Login | The Pythonomicon
{% endblock %}

{% block content %}
<div class="login-page sidebar-collapse">
    <div class="page-header" filter-color="orange">
        <div class="page-header-image" style="background-image:url(static/img/login.jpg)"></div>
        <div class="container">
            <div class="col-md-4 content-center">
                <div class="card card-login card-plain">
                    <form class="form" method="post" action="{{ url_for('app.login') }}">
                        {{ form.hidden_tag() }}
                        <div class="header header-primary text-center">
                            <div class="logo-container">
                                <img src="static/img/now-logo.png" alt="">
                            </div>
                        </div>
                        <div class="content">
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons users_circle-08"></i>
                                </span>
                                {{ form.username(class="form-control") }}
                                <!-- <input type="text" name="username" class="form-control" placeholder="Username..."> -->
                            </div>
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                </span>
                                {{ form.password(class="form-control") }}
                                <!-- <input type="password" name="password" placeholder="Password" class="form-control" /> -->
                            </div>
                        </div>
                        <div class="footer text-center">
                            {{ form.submit(class="btn btn-primary btn-round btn-lg btn-block") }}
                            <!-- <input type="submit" class="btn btn-primary btn-round btn-lg btn-block"> -->
                        </div>
                        <div class="pull-left">
                            <h6>
                                <a href="{{ url_for('app.signup') }}" class="link">Create Account</a>
                            </h6>
                        </div>
                        <div class="pull-right">
                            <h6>
                                <a href="#pablo" class="link">Need Help?</a>
                            </h6>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/newpost.html
{% extends "layouts/base.html" %}
{% block title %}
  New Post | The Pythonomicon
{% endblock %}

{% block content %}
<!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <form name="addForm" id="addForm" method="post" action="{{ url_for('app.new_post') }}" novalidate>
            {{ form.hidden_tag() }}
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                {{ form.title(class="form-control", id="title", placeholder="Title...") }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Subtitle</label>
                {{ form.subtitle(class="form-control", id="subtitle", placeholder="Subtitle...") }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Content</label>
                {{ form.content(class="form-control", id="content", placeholder="Content...", rows="10") }}
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              {{ form.submit(class="btn btn-primary", id="sendMessageButton") }}
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock%}

app/templates/post.html
{% extends "layouts/base.html" %}
{% block title %}
  The Pythonomicon - By SmyhkTech
{% endblock %}

{% block content %}
<!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.content|safe }}
          </div>
        </div>
      </div>
    </article>
{% endblock %}

app/templates/signup.html
{% extends "layouts/base.html" %}
{% block title %}
  Create Account | The Pythonomicon
{% endblock %}

{% block content %}
<div class="login-page sidebar-collapse">
    <div class="page-header" filter-color="orange">
        <div class="page-header-image" style="background-image:url(static/img/login.jpg)"></div>
        <div class="container">
            <div class="col-md-4 content-center">
                <div class="card card-login card-plain">
                    <form class="form" method="post" action="{{ url_for('app.signup') }}">
                        {{ form.hidden_tag() }}
                        <div class="header header-primary text-center">
                            <div class="logo-container">
                                <img src="static/img/now-logo.png" alt="">
                            </div>
                        </div>
                        <div class="content">
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons users_circle-08"></i>
                                </span>
                                {{ form.username(class="form-control", placeholder="Username...") }}
                                <!-- <input type="text" class="form-control" placeholder="Username..."> -->
                            </div>
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_email-85"></i>
                                </span>
                                {{ form.email(class="form-control", placeholder="Email...") }}
                                <!-- <input type="text" class="form-control" placeholder="Email..."> -->
                            </div>
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                </span>
                                {{ form.password(class="form-control", placeholder="Password...") }}
                                <!-- <input type="password" placeholder="Password..." class="form-control" /> -->
                            </div>
                        </div>
                        <div class="footer text-center">
                            {{ form.submit(class="btn btn-primary btn-round btn-lg btn-block") }}
                            <!-- <input type="submit" class="btn btn-primary btn-round btn-lg btn-block"> -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}